apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetapp
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnetapp
  template:
    metadata:
      labels:
        app: dotnetapp
    spec:
      containers:
      - name: dotnetapp
        image: acrdesafiodevops.azurecr.io/dotnetapp:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr-secret
      # segredo k8s que armazena do acr para poder puxar imagens