apiVersion: v1
kind: Service
metadata:
  name: dotnetapp-service
  namespace: dev
spec:
  selector:
    app: dotnetapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer